import { BookOpen, CalendarDays, Headphones, Image, LoaderCircle, Mic2, Pause, Play, Sparkles, Tag, UsersRound } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { PodcastDialog } from "../components/PodcastDialog";
import { PodcastQuickActions } from "../components/PodcastQuickActions";
import { PodcastSharePanel } from "../components/PodcastSharePanel";
import { HighlightSharePanel } from "../components/HighlightSharePanel";
import { listHighlightWorks, trashHighlightWork, type HighlightWork } from "../services/highlightApi";
import { listTimeline, type TimelineItem, type TimelineKind } from "../services/lifecycleApi";
import { listPodcastProducts, trashPodcastProduct, type PodcastProduct } from "../services/podcastApi";

const kindCopy:Record<TimelineKind,{label:string;icon:typeof Mic2}>={recording:{label:"录音",icon:Mic2},moment:{label:"高光",icon:Sparkles},comic:{label:"漫画",icon:Image},podcast:{label:"播客",icon:Headphones}};
const inDate=(value:string,from:string,to:string)=>{const time=new Date(value).getTime();return(!from||time>=new Date(`${from}T00:00:00+08:00`).getTime())&&(!to||time<=new Date(`${to}T23:59:59+08:00`).getTime())};
export function podcastProductTimelineItem(product:PodcastProduct):TimelineItem{return{id:product.podcast_version_id,kind:"podcast",title:product.title,subtitle:product.description||"家庭声音播客",status:"product-v2",created_at:product.created_at,recording_id:product.recording_id,target_path:`/recordings/${product.recording_id}/podcast`,member_ids:[]}}

export function TimelinePage(){const navigate=useNavigate(),{session}=useAuth();const audio=useRef<HTMLAudioElement>(null);
  const[items,setItems]=useState<TimelineItem[]>([]),[products,setProducts]=useState<PodcastProduct[]>([]),[highlights,setHighlights]=useState<HighlightWork[]>([]),[kind,setKind]=useState<TimelineKind|"">(""),[member,setMember]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[tag,setTag]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[playing,setPlaying]=useState<string|null>(null),[sharePodcast,setSharePodcast]=useState<PodcastProduct|null>(null),[shareHighlight,setShareHighlight]=useState<HighlightWork|null>(null),[deleting,setDeleting]=useState<HighlightWork|null>(null),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
  const [deletingPodcast,setDeletingPodcast]=useState<PodcastProduct|null>(null);
  useEffect(()=>{let active=true;setLoading(true);setError("");Promise.all([listTimeline({content_type:kind,member_id:member,date_from:from,date_to:to}),listPodcastProducts(tag||undefined),listHighlightWorks()]).then(([result,nextProducts,nextHighlights])=>{if(!active)return;setProducts(nextProducts);setHighlights(nextHighlights);const base=result.items.filter(item=>item.kind!=="podcast"&&item.kind!=="moment");const podcastItems=nextProducts.filter(p=>(!kind||kind==="podcast")&&!member&&inDate(p.created_at,from,to)).map(podcastProductTimelineItem);const highlightItems=nextHighlights.filter(h=>(!kind||kind==="moment")&&(!member||h.member_ids.includes(member))&&inDate(h.created_at,from,to)).map(h=>({id:h.id,kind:"moment" as const,title:h.title,subtitle:h.quote,status:h.audio_status,created_at:h.created_at,recording_id:h.recording_id,target_path:`/highlights/${h.id}`,member_ids:h.member_ids}));setItems([...base,...podcastItems,...highlightItems].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()))}).catch(()=>active&&setError("时间线暂时无法读取，请稍后重试。")).finally(()=>active&&setLoading(false));return()=>{active=false}},[kind,member,from,to,tag,reload]);
  const productMap=useMemo(()=>new Map(products.map(p=>[p.podcast_version_id,p])),[products]),highlightMap=useMemo(()=>new Map(highlights.map(h=>[h.id,h])),[highlights]);
  const tags=Array.from(new Set(products.flatMap(p=>p.available_tags.map(t=>t.name))));
  const play=async(work:HighlightWork)=>{if(!audio.current||!work.audio_url)return;if(playing===work.id){audio.current.pause();setPlaying(null);return}audio.current.src=work.audio_url;try{await audio.current.play();setPlaying(work.id)}catch{setError("这段高光暂时无法播放。")}};
  const remove=async()=>{if(!deleting&&!deletingPodcast)return;setBusy(true);try{if(deleting)await trashHighlightWork(deleting.id);else await trashPodcastProduct(deletingPodcast!.recording_id);setDeleting(null);setDeletingPodcast(null);setReload(v=>v+1)}catch{setError("作品未能移入回收站，请重试。") }finally{setBusy(false)}};
  return <div className="timeline-page"><header className="timeline-header"><span className="section-kicker">SOUND POSTCARDS</span><h1>声音明信片</h1><p>把一句话、一张竖版图片和一段家人原声，寄给未来的自己。</p></header>
    <section className="timeline-filters"><label><BookOpen size={15}/><select value={kind} onChange={e=>setKind(e.target.value as TimelineKind|"")}><option value="">全部内容</option>{Object.entries(kindCopy).map(([value,copy])=><option key={value} value={value}>{copy.label}</option>)}</select></label><label><UsersRound size={15}/><select value={member} onChange={e=>setMember(e.target.value)}><option value="">全部家人</option>{session?.family?.members.map(m=><option key={m.id} value={m.id}>{m.nickname}</option>)}</select></label><label><CalendarDays size={15}/><input aria-label="开始日期" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span>至</span><input aria-label="结束日期" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label><Tag size={15}/><select value={tag} onChange={e=>{setTag(e.target.value);if(e.target.value)setKind("podcast")}}><option value="">全部标签</option>{tags.map(t=><option key={t} value={t}>#{t}</option>)}</select></label></section>
    {loading?<section className="progress-loading"><LoaderCircle className="spin"/><p>正在整理家庭时光…</p></section>:error?<p className="moment-review-error" role="alert">{error}<button className="text-action" onClick={()=>setReload(v=>v+1)}>重试</button></p>:items.length?<section className="timeline-card-stream">{items.map((item,index)=>{const copy=kindCopy[item.kind],Icon=copy.icon,date=new Date(item.created_at),product=productMap.get(item.id),highlight=highlightMap.get(item.id),cover=product?.cover?.thumbnail_url||product?.cover?.url||highlight?.cover?.thumbnail_url||highlight?.cover?.url;return <div key={`${item.kind}-${item.id}`} className="timeline-card-event"><div className="timeline-card-date"><strong>{date.getDate()}</strong><span>{date.toLocaleDateString("zh-CN",{month:"short"})}</span><time>{date.toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}</time></div><div className={`timeline-card-node ${item.kind}`}><Icon size={17}/></div><article className={`timeline-info-card ${item.kind}`}>
      <Link className="timeline-card-main" to={item.target_path}><div className={`timeline-card-visual ${cover?"has-cover":""}`} style={cover?{backgroundImage:`url(${cover})`}:undefined}>{!cover&&<Icon size={31}/>}<span>{product?"完整作品":highlight?"声音明信片":copy.label}</span></div><div className="timeline-card-copy"><span>{highlight?"声音明信片":copy.label} · {index===0?"最近更新":date.toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"})}</span><h2>{item.title}</h2><p>{item.subtitle}</p>{product&&product.tags.length>0&&<div className="timeline-card-tags">{product.tags.map(t=><span key={t.id}>#{t.name}</span>)}</div>}<strong>{product?"打开完整作品":highlight?"打开声音明信片":"查看这一刻"}<span aria-hidden="true">→</span></strong></div></Link>
      {highlight&&<button className="timeline-highlight-play" aria-label={playing===highlight.id?"暂停高光":"播放高光"} disabled={!highlight.audio_url} onClick={()=>void play(highlight)}>{playing===highlight.id?<Pause size={14}/>:<Play size={14}/>}</button>}
      {(product||highlight)&&<PodcastQuickActions title={item.title} onEdit={()=>navigate(product?`/recordings/${product.recording_id}/podcast?edit=1`:`/highlights/${highlight!.id}?edit=1`)} onShare={()=>product?setSharePodcast(product):setShareHighlight(highlight!)} onDelete={()=>highlight?setDeleting(highlight):setDeletingPodcast(product!)}/>}</article></div>})}</section>:<section className="timeline-empty"><CalendarDays size={34}/><h2>还没有符合条件的时光</h2><p>从播客创作页保存一个值得留下的高光。</p><button className="primary-button" onClick={()=>navigate("/upload")}>上传录音</button></section>}
    <audio ref={audio} onEnded={()=>setPlaying(null)}/>
    {sharePodcast&&<PodcastDialog title={`分享 · ${sharePodcast.title}`} onClose={()=>setSharePodcast(null)}><PodcastSharePanel product={sharePodcast}/></PodcastDialog>}
    {shareHighlight&&<PodcastDialog title={`分享 · ${shareHighlight.title}`} onClose={()=>setShareHighlight(null)}><HighlightSharePanel work={shareHighlight}/></PodcastDialog>}
    {(deleting||deletingPodcast)&&<PodcastDialog title="移至回收站？" busy={busy} onClose={()=>{setDeleting(null);setDeletingPodcast(null)}}><p className="podcast-delete-title">{deleting?.title||deletingPodcast?.title}</p><p className="podcast-dialog-description">作品将从成长时间线移除，已有分享链接会失效。你可以在回收站恢复。</p><div className="podcast-dialog-actions"><button data-initial-focus className="secondary-button" disabled={busy} onClick={()=>{setDeleting(null);setDeletingPodcast(null)}}>取消</button><button className="podcast-danger-button" disabled={busy} onClick={()=>void remove()}>{busy?"正在移入…":"确认移至回收站"}</button></div></PodcastDialog>}
  </div>}
